name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: github/eslint-action@v3
        with:
          eslint-version: '7.x'
          working-directory: ./src